### ISSUE TITLE
Flicker when update and unmount used together

### ISSUE THREAD

**Issue by fabien** [riot/animore#1]
@GianlucaGuarini this is great, I only noticed this right now. It's exactly what I was looking for in a Riot implementation. Thanks!

Two questions:

- why did you implement it as a tag instead of a mixin?
- is there any way to prevent the flicker/jerky movement when deleting (unmounting) an item, when update is also specified? Perhaps this is caused by the _flipr_ effect, not correctly taking the height or something? Or perhaps an easing issue? Without any update specified, it works nicely. 

Please see this adapted plunkr: http://plnkr.co/edit/dvwKmpxTz3noUAbfyZcV?p=preview

Motion on unmount could be a bit more fluid in general (even without `update`), and with your original plunkr the animations became slower and slower when adding more items (20+) on my iPad (Pro) this morning. I haven't tested my updated plunkr, but I suspect the same to happen (edit: strangely enough, my plunkr appears pretty smooth compared to yours).

I wonder if this is on Anime or Riot's end of things?

**Comment by GianlucaGuarini** [comment]
> why did you implement it as a tag instead of a mixin?

it could be implemented also as a mixin but via tag I am sure to control the `this.root` element

> is there any way to prevent the flicker/jerky movement when deleting (unmounting) an item, when update is also specified? Perhaps this is caused by the flipr effect, not correctly taking the height or something? Or perhaps an easing issue? Without any update specified, it works nicely.

it seems that when I do the `update` flip the tag disappearing is twice in the DOM together with its [clone](https://github.com/riot/animore/blob/361733c6bef575d525dad211074d9c6f35f9a080/lib/animore.js#L65) I will fix it asap

> Motion on unmount could be a bit more fluid in general (even without update), and with your original plunkr the animations became slower and slower when adding more items (20+) on my iPad (Pro) this morning. I haven't tested my updated plunkr, but I suspect the same to happen (edit: strangely enough, my plunkr appears pretty smooth compared to yours).

I couldn't test it on the iPad but it sounds a bit strange, I will check this also asap thanks for reporting it

**Comment by GianlucaGuarini** [comment]
after digging a bit the code it appears that this is not really a bug: using `update` and `unmount` on the same elements you run 2 animations in parallel so the `height` transition happens together with the transform transition of the items around the unmounting element. A possible workaround could be [this](http://plnkr.co/edit/CWCoJDQliWhRSrfr9Siu?p=preview) so the update animation has no effect during the unmount.
Regarding the performance issues you had I don't know what to say since I have tested `riot-animore` on an iPad Air and they were pretty smooth

**Comment by BrockAtkinson** [comment]
If you keep your eyes peeled, even your project shows this jittering/flickering when animation begins - it only takes a split-second, but it's there (Windows and Android). I think what's happening is it's rendering the object (or a clone) in its final position for one frame before beginning the full animation. It becomes more obvious when templates increase in complexity.

I've gotta say, this is a wonderful library, very smooth animations with a seamless setup.

**Comment by ShiMeiWo** [comment]
The issue becomes more understandable when you enlarge the duration and set easing 'linear':
http://plnkr.co/edit/Jb8wvQMb12rWOi1fjdK7?p=preview

**Comment by GianlucaGuarini** [comment]
it's because the margin top/bottom isn't animated [fixed here](http://plnkr.co/edit/WStYBACBS4gWpmCa3qQe?p=preview)
